<?php
namespace App\Helpers;

class SeederHelper
{
    public static function genres()
    {
        return collect([
            (object) [
                'name'               => 'Fantasy',
                'brief'              => 'Fantasy fiction with imaginary worlds and magic',
                'prompt_instruction' => 'Fantasy-oriented stories require careful consideration of an invented world with consistent internal rules, a defined magic system with limitations and cost, memorable creatures and peoples, a rich mythology and history, and a conflict that rises naturally from the setting. The planning process should analyze how the world is built, what rules bound magic and how they shape conflict, how supernatural or fantastical elements are introduced and sustained, and how the setting directly influences character choices and story progression rather than serving only as decoration. World planning should consider geography, cultures, power structures, laws of the world, magic sources and their costs, technology level, mythology, and the history that drives present tensions. Character planning should consider heroes and villains shaped by their world, belief systems grounded in the setting, personal stakes tied to world forces, and how abilities or limitations create meaningful moral and practical challenges. The story structure should consider a clear arc where fantastical elements escalate logically, world-altering stakes, and a resolution consistent with the established rules. When combined with other genres, integrate these fantasy world and magic elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Dark Fantasy',
                'brief'              => 'Dark and mysterious fantasy stories',
                'prompt_instruction' => 'Dark fantasy-oriented stories require careful consideration of a grim, morally ambiguous world where magic or supernatural forces come at a steep cost, corruption and horror coexist with fantastical elements, and the line between hero and villain is blurred. The planning process should analyze the darkness of the world, the price of power and magic, the moral compromises characters must make, the creeping horror woven through the setting, and how hopeless or desperate circumstances shape motivation without removing meaning. World planning should consider oppressive atmospheres, decaying or dangerous settings, supernatural threats, corrupting forces, societal decay, and a sense that the world itself is an antagonist. Character planning should consider morally grey protagonists, flawed or compromised heroes, antagonists with understandable or tragic motives, internal corruption, and the cost of victory on personal integrity. The story structure should consider a bleak but meaningful progression, where hope is hard-won, sacrifices carry real weight, and endings align with the tonal darkness while remaining emotionally satisfying. When combined with other genres, integrate these grim fantasy and moral-ambiguity elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Historical Fiction',
                'brief'              => 'Stories based on historical events and periods',
                'prompt_instruction' => 'Historical fiction-oriented stories require careful consideration of an authentic time and place, credible period detail, the influence of real events and social structures on characters, and a narrative that stays true to the era while remaining dramatically engaging. The planning process should analyze the chosen historical period, the accuracy of its setting, the everyday lives and constraints of people in that era, and how real historical forces shape personal stories. Setting planning should consider the time period, geography, politics, class and social structures, customs and daily life, technology, economy, and the historical events that frame the narrative. Character planning should consider believable period-appropriate behaviour, characters constrained and motivated by their era, and conflict driven by the values, expectations, and opportunities of the time. The story structure should consider how historical turning points create tension, how personal stakes intersect with larger events, and an ending consistent with the historical setting while remaining emotionally resonant. When combined with other genres, integrate these historical and period-authenticity elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Family Drama',
                'brief'              => 'Stories about family relationships and emotions',
                'prompt_instruction' => 'Family drama-oriented stories require careful consideration of the bonds, conflicts, secrets, and long-standing tensions within a family unit, all driven by believable emotional stakes rather than action or spectacle. The planning process should analyze the family structure, the history between members, the unspoken resentments and loyalties, and how a central family conflict intensifies over time. Character planning should consider each family member\'s distinct voice and motivation, generational differences, rivalries and alliances, buried wounds, and how love and obligation coexist with disappointment and anger. Story planning should consider realistic dialogue-driven conflict, small moments that echo large emotional truths, escalating domestic tension, and how the resolution confronts rather than sidesteps the family\'s deeper issues. The emotional arc should prioritise authenticity, meaningful reconciliation or acceptance, and character growth rooted in family identity. When combined with other genres, integrate these family and emotional-dynamic elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Romance',
                'brief'              => 'Love and relationship based stories',
                'prompt_instruction' => 'Romance-oriented stories require careful consideration of the central relationship, the emotional and sexual chemistry between the pair, the obstacles that keep them apart, and the believable growth that brings them together. The planning process should analyze the two central figures, what draws them together, what drives them apart, and how the connection deepens through meaningful interaction rather than coincidence. Character planning should consider complementary but distinct personalities, genuine attraction supported by interaction, personal flaws that create friction, and individual arcs of growth that must be resolved before commitment is earned. Story planning should consider the meet-between dynamics, escalating emotional and external obstacles, tender and charged moments, and a satisfying resolution where being together is a believable choice. The emotional arc should prioritise authentic attraction, vulnerability, communication, and mutual change, avoiding connection dependent purely on fate or convenience. When combined with other genres, integrate these relationship-development and chemistry elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Mystery',
                'brief'              => 'Mystery and investigation stories',
                'prompt_instruction' => 'Mystery-oriented stories require careful consideration of a central puzzle, the investigation that unwinds it, carefully placed clues and red herrings, a credible set of suspects, and a solution supported by the presented evidence. The planning process should analyze the nature of the mystery, what information is hidden and how it is revealed, the fairness of the clue trail, and how the reader is invited to solve it alongside the protagonist. The case itself should be planned around a clear question or crime, a timeline of events, physical and circumstantial evidence, and a chain of deduction that connects every clue to the solution. Character planning should consider an investigator with reason to care, suspects with plausible motives and opportunity, witnesses with partial or misleading knowledge, and a culprit whose identity is surprising yet consistent with the facts. The story structure should consider when each clue is uncovered, how red herrings mislead without cheating, the escalation toward the reveal, and a resolution that explains the whole puzzle clearly. When combined with other genres, integrate these investigation and evidence elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Thriller',
                'brief'              => 'Suspenseful and exciting stories',
                'prompt_instruction' => 'Thriller-oriented stories require careful consideration of escalating danger, psychological tension, hidden motives, unpredictable events, antagonist motivations, and strong suspense progression. The planning process should analyze how tension is created, how threats evolve, how characters respond under pressure, and how major reveals influence the direction of the story. Character planning should consider strong motivations, personal vulnerabilities, internal conflicts, and opposing forces that create meaningful challenges. The story structure should consider pacing control, emotional intensity, unexpected turns, and a satisfying climax that resolves the central conflict. When combined with other genres, integrate these thriller elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Horror',
                'brief'              => 'Scary and horror fiction stories',
                'prompt_instruction' => 'Horror-oriented stories require careful consideration of the source of fear, atmospheric dread, psychological and visceral tension, escalating unease, and a narrative that confronts the characters with something truly threatening. The planning process should analyse the central horror concept, how fear manifests and intensifies, what the characters lose or sacrifice, and how vulnerability is sustained throughout. Character planning should consider how fear exposes flaws and tests resolve, characters who respond in dramatically useful ways, and antagonists or forces that are deeply unsettling or unknowable. Story planning should consider sustained tension, the careful withholding and release of information, mounting dread before confrontation, and an ending that is tonally appropriate — where horror is confronted, escaped, or accepted. The emotional arc should prioritise unease, dawning awareness, escalating vulnerability, and a climax that earns its fear through established stakes and meaning. When combined with other genres, integrate these horror and tension elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Science Fiction',
                'brief'              => 'Science based futuristic fiction',
                'prompt_instruction' => 'Science fiction-oriented stories require careful consideration of a plausible or rigorously imagined technological, scientific, or societal concept, and how that concept transforms the human experience. The planning process should analyse the speculative concept, the rules and limits of the technology or science, how it alters daily life, ethics, power structures, and personal relationships. World planning should consider the technological level, how the speculative concept has shaped society, political and economic consequences, scientific rationale, and how ordinary people live within the changed world. Character planning should consider how characters respond to, exploit, or struggle against the changed world, and how the speculative concept creates or deepens their central dilemma. Story planning should consider how the speculative idea drives the conflict, how rules and consequences are clearly established, and how the resolution engages meaningfully with the idea rather than simply borrowing its imagery. When combined with other genres, integrate these science fiction and speculative-concept elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Adventure',
                'brief'              => 'Journey and exploration based stories',
                'prompt_instruction' => 'Adventure-oriented stories require careful consideration of a clear journey or exploration, compelling destinations, tangible danger, a driving goal, and characters tested by what they encounter along the way. The planning process should analyse the objective of the journey, the geography and obstacles involved, how characters grow through exposure to new places and challenges, and how the goal shifts as the story unfolds. World planning should consider diverse locations, the dangers inherent in each, the cultures or forces encountered, how the environment acts as obstacle or aid, and what resources the characters have. Character planning should consider resourceful, resilient protagonists, companion dynamics, rivals and threats encountered, and how the journey transforms the characters\' understanding or values. Story planning should consider rising stakes through escalating challenges, meaningful detours and discoveries, and a climax where the journey itself delivers the character to their true challenge. When combined with other genres, integrate these journey, exploration and challenge elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Biography',
                'brief'              => 'Life stories of real people',
                'prompt_instruction' => 'Biography-oriented stories require careful consideration of a real subject\'s identity, the arc of their public and private life, the context that shaped them, and what their story reveals about human experience. The planning process should analyse the subject\'s defining qualities, the pivotal events of their life, the context that influenced them, and how the narrative balances factual accuracy with readable structure. Subject planning should consider birth and background, formative experiences, defining achievements, struggles and failures, relationships and influence, and the lasting impact of their actions. Story planning should consider how to structure the life into a coherent narrative arc, which periods or moments are most dramatically significant, and how to present the subject with honesty and depth. The narrative should prioritise verifiable truth, meaningful context, and a clear sense of who this person was and why their life matters. When combined with other genres, integrate these biographical and subject-arc elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Autobiography',
                'brief'              => 'Life story written by the person themselves',
                'prompt_instruction' => 'Autobiography-oriented stories require careful consideration of a first-person subject reflecting on their own life with honesty, self-awareness, and the understanding that memory and perspective shape the story. The planning process should analyse the subject\'s voice and honesty, what periods or moments they choose to tell, how they interpret their own choices, and what the narrative reveals about their identity. Subject planning should consider formative childhood experiences, personal turning points, achievements and regrets, relationships, the values that guided decisions, and how the subject has changed over time. Story planning should consider a coherent arc shaped by the subject\'s own understanding, which periods receive most attention, how to handle difficult or shameful moments honestly, and what the narrative ultimately wants the reader to take from this life. The emotional arc should prioritise authenticity, self-reflection, and a clear sense of who this person is when only their own word is the record. When combined with other genres, integrate these autobiographical and self-reflection elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'History',
                'brief'              => 'Historical books and events',
                'prompt_instruction' => 'History-oriented works require careful consideration of the actual events, their causes and consequences, the interplay of people, place and time, and a presentation grounded in evidence while remaining accessible. The planning process should analyse the historical subject, why the events matter, the sources available, and how the narrative connects events into comprehensible causation rather than a bare chronology. Historical planning should consider the era, key figures and institutions, geographic setting, prior causes, the sequence and mechanics of events, and their lasting consequences. Content planning should consider which elements are essential to the reader\'s understanding, how to weigh competing interpretations, the limits of the sources, and how to stay faithful to the record while ordering facts into a clear narrative. When combined with other genres, integrate these historical-evidence and causation elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Philosophy',
                'brief'              => 'Books about ideas and philosophy',
                'prompt_instruction' => 'Philosophy-oriented works require careful consideration of a central question or set of ideas, the reasoning that supports them, and the implications those ideas carry for understanding. The planning process should analyse the philosophical question being explored, the position or positions argued, the evidence and reasoning offered, and how the ideas relate to lived experience and human concerns. Conceptual planning should consider the key terms and their meanings, the assumptions embedded in each position, the logic of the argument, how objections or counter-arguments are addressed, and the practical or moral implications of the ideas. Content planning should consider clarity over jargon, logical structure, the use of examples and thought experiments, and a progression of ideas that deepens understanding. When combined with other genres, integrate these philosophical and conceptual elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Self Help',
                'brief'              => 'Personal development and improvement books',
                'prompt_instruction' => 'Self help-oriented works require careful consideration of a clear target audience, a core principle or framework, and actionable guidance the reader can apply directly. The planning process should analyse the specific problem or aspiration being addressed, who the reader is, what prevents them from achieving it, and what concrete steps will move them forward. Content planning should consider a focused framework or set of principles, clearly defined practical steps, real-world examples, how the advice accounts for common obstacles, and how the reader can measure or notice progress. Structure planning should consider a logical progression from understanding to action, clarity of language, avoidance of unnecessary abstraction, and an honest presentation of what the advice can and cannot achieve. When combined with other genres, integrate these practical-guidance and self-development elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Psychological',
                'brief'              => 'Stories focused on human mind and emotions',
                'prompt_instruction' => 'Psychological-oriented stories require careful consideration of how characters think, feel, and perceive reality, where internal experience shapes the narrative, and the gap between appearance and inner truth creates tension. The planning process should analyse the inner lives of the characters, what they fear, desire, and avoid, and how their mental and emotional states drive their actions and the direction of the story. Character planning should consider distinct psychological profiles, emotional patterns, defence mechanisms, internal conflicts, and how perception or memory may distort the characters\' understanding of events. Story planning should consider carefully revealed motivations, the tension between what characters show and what they feel, how psychological pressure builds over time, and a resolution that addresses the inner conflict rather than only external events. When combined with other genres, integrate these psychological and inner-life elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Supernatural',
                'brief'              => 'Stories involving supernatural elements',
                'prompt_instruction' => 'Supernatural-oriented stories require careful consideration of forces, beings, or occurrences beyond the natural world, how they are perceived and feared, and where they intersect with the lives of ordinary characters. The planning process should analyse the nature of the supernatural element, its rules or lack of rules, how it manifests within the world, and how this beyond-the-ordinary presence shapes the story. World planning should consider the source of the supernatural, whether it follows consistent rules or remains mysterious, how it affects daily life and belief, and the costs or consequences of interacting with it. Character planning should consider how characters respond to the inexplicable, what they believe, and how encountering the supernatural tests or changes them. Story planning should consider a balance between the ordinary and the extraordinary, how suspense or wonder is sustained, and a resolution that honours the established nature of the supernatural force. When combined with other genres, integrate these supernatural and otherworldly elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Crime',
                'brief'              => 'Crime related fiction stories',
                'prompt_instruction' => 'Crime-oriented stories require careful consideration of the nature of the criminal act, how it is investigated, the motives and methods of those involved, and the moral and social questions the crime raises. The planning process should analyse the crime itself, its mechanics and motives, the pursuit of those responsible, and how the crime reverberates through the affected people and institutions. Investigation planning should consider the evidence available, the sequence of events, the suspects and their access and motive, and how the case is built up and unravels across the narrative. Character planning should consider the criminals\' plausible psychology and method, the investigators\' skills and limitations, and the victims\' and witnesses\' experiences of the crime. Story planning should consider how the crime is uncovered, the obstacles and setbacks, the tension of pursuit, and a resolution that fits the evidence and faces the consequences of the act. When combined with other genres, integrate these crime and investigation elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Political Fiction',
                'brief'              => 'Stories involving politics and society',
                'prompt_instruction' => 'Political fiction-oriented stories require careful consideration of power dynamics, the machinery of institutions and government, ideology, and how broad social forces shape personal choices and conflicts. The planning process should analyse the political system depicted, the struggle for power within it, the motivations of those involved, and how individual ambition intersects with public consequence. World planning should consider the structure of government, political parties or factions, law and its enforcement, economics, media, and the social conditions that create political tension. Character planning should consider politicians, officials, activists and ordinary citizens, their competing ambitions and principles, the compromises power demands, and the personal costs of political engagement. Story planning should consider strategic maneuvering, alliances and betrayals, public and private conflict, rising stakes as power is contested, and a resolution that reveals the outcome and meaning of the struggle. When combined with other genres, integrate these political and power-dynamics elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'War',
                'brief'              => 'Stories based on wars and conflicts',
                'prompt_instruction' => 'War-oriented stories require careful consideration of the conflict itself, its causes and conduct, the experience of combat and its aftermath, and how war transforms the people caught within it. The planning process should analyse the nature of the conflict, its historical or imagined setting, the strategy and moments of combat, and the human cost carried before, during, and after the fighting. Setting and world planning should consider the scale and type of conflict, the tactics and technology involved, the home front as well as the battlefield, and how the war shapes the society that wages it. Character planning should consider soldiers and civilians, leaders and the led, the pressures of combat, fear and courage, and the losses that mark them permanently. Story planning should consider the progression of the war, moments of intense action balanced against their human weight, withdrawal from easy glorification or condemnation, and the cost of resolution. When combined with other genres, integrate these conflict and war-experience elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Young Adult',
                'brief'              => 'Stories for young adult readers',
                'prompt_instruction' => 'Young adult-oriented stories require careful consideration of the adolescent and young-adult experience, growth and self-discovery, and conflict that speaks to the age and concerns of the audience. The planning process should analyse the coming-of-age journey, the identity questions characters face, and how their external world and inner sense of self evolve together. Character planning should consider genuine, relatable protagonists navigating self-identity, belonging, friendship and first relationships, pressure from family and society, and the discovery of personal agency. Story planning should consider challenges suited to the audience\'s stage of life, emotional honesty, growth through meaningful choice and consequence, and a resolution that reflects earned maturity rather than simple resolution of surface problems. When combined with other genres, integrate these coming-of-age and identity-development elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Children',
                'brief'              => 'Books for children',
                'prompt_instruction' => 'Children-oriented stories require careful consideration of the age of the intended reader, language and themes appropriate to that age, and a narrative that is clear, engaging, and emotionally meaningful to a child. The planning process should analyse the target age range and its reading level, the themes suitable for that stage, and how the story entertains while supporting curiosity and understanding. Content planning should consider simple, clear language, an accessible structure, memorable characters and situations a child can grasp, and lessons or insights offered without being heavy-handed. Story planning should consider an engaging pace, familiar but imaginative settings, a conflict a young reader can understand, and a hopeful, satisfying resolution that rewards the journey and reinforces positive values. When combined with other genres, integrate these age-appropriate and child-oriented elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Poetry',
                'brief'              => 'Poetry and verses',
                'prompt_instruction' => 'Poetry-oriented works require careful consideration of the intended emotional or thematic core, the shape of the language and form, and how sound, imagery and rhythm carry meaning beyond literal statement. The planning process should analyse the central feeling or idea, the poetic form most suited to it, and how each line earns its place through image, sound and implication. Form planning should consider the chosen structure, meter and rhythm, rhyme or its absence, stanza shape, and the pace and musicality best serving the subject. Content planning should consider precise imagery, suggestive use of language, emotional tone, and the restraint that lets meaning unfold rather than being stated. The reader\'s experience should centre the emotional and sensory response the poem is designed to create, consistent with its form and intention. When combined with other genres, integrate these poetic and expressive-language elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],

            (object) [
                'name'               => 'Short Story',
                'brief'              => 'Short fiction stories',
                'prompt_instruction' => 'Short story-oriented works require careful consideration of a single, focused effect, economical storytelling, and the discipline of implying the world rather than exhaustively describing it. The planning process should analyse the central character, the pivotal moment or turning point, and how a tight narrative concentrates meaning within a limited length. Content planning should consider a single strong premise, a narrow focus, deliberate selection of detail, and restraint that lets suggestion carry as much weight as statement. Story planning should consider entering the narrative as late as possible, a swiftly established situation, a clear progression toward the defining moment, and an ending that leaves a lasting charge. The reader\'s experience should centre the tightness and unity that mark the form, where every element serves a single coherent effect. When combined with other genres, integrate these focused and economical-story elements with the requirements of the additional genres while avoiding duplicate planning elements.',
            ],
        ]);
    }
}
